name: Script run

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: echo
        run: echo "teste"
      - name: script
        run: |
          node -v
          npm --version 
      - name: python script
        run: |
          import datetime
          print(datetime.datetime.now())
        shell: python
  run-windows-command:
    # needs: [run-shell-command]
    runs-on: windows-latest
    steps:
      - name: powershell
        run: powershell Invoke-WebRequest -Uri https://www.google.com
        shell: powershell
      - name: bash
        run: pwd
        shell: bash